language: perl
perl:
  - "5.26"

install:
  - wget https://github.com/BenLangmead/bowtie2/releases/download/v2.2.9/bowtie2-2.2.9-linux-x86_64.zip -O ~/bin/bowtie2-2.2.9-linux-x86_64.zip
  - unzip ~/bin/bowtie2-2.2.9-linux-x86_64.zip -d ~/bin/
  - mv ~/bin/bowtie2-2.2.9/* ~/bin/ 
  
script:
  - "./bismark_genome_preparation --verbose ./travis_files/"
  - "./bismark --genome ./travis_files/ ./travis_files/test_R1.fastq.gz"
