language: perl
perl:
  - "5.26"
  - "5.24"
  - "5.22"
  
install: true

script:
  - "./bismark_genome_preparation --verbose ."
  - "./bismark_genome_preparation --verbose --bowtie1 ."
  - "./bismark --genome ./travis_files/ ./travis_files/test_R1.fastq.gz"
