language: perl
perl:
  - "5.26"

install:
  # Installing Bowtie 2
  - wget https://github.com/BenLangmead/bowtie2/releases/download/v2.2.9/bowtie2-2.2.9-linux-x86_64.zip -O ~/bin/bowtie2-2.2.9-linux-x86_64.zip
  - unzip ~/bin/bowtie2-2.2.9-linux-x86_64.zip -d ~/bin/
  - mv ~/bin/bowtie2-2.2.9/* ~/bin/ 
  # Installing Bowtie 1
  - wget https://sourceforge.net/projects/bowtie-bio/files/bowtie/1.2.2/bowtie-1.2.2-linux-x86_64.zip/download -O ~/bin/bowtie-1.2.2-linux-x86_64.zip
  - unzip ~/bin/bowtie-1.2.2-linux-x86_64.zip -d ~/bin/
  - mv ~/bin/bowtie-1.2.2-linux-x86_64/bowtie* ~/bin/ 
   # installing Samtools
  - wget https://github.com/samtools/samtools/releases/download/1.9/samtools-1.9.tar.bz2
  - tar xjvf samtools-1.9.tar.bz2
  - cd samtools-1.9
  - ./configure --prefix=/home/travis/samtools/
  - make -j 10
  - make install
  - export PATH=/home/travis/samtools/bin:$PATH
  - samtools --version  
  - cd /home/travis/build/FelixKrueger/Bismark/
  
script:
  # Using Bowtie 2
  - "./bismark_genome_preparation --verbose ./travis_files/"
  ## PE
  - "./bismark --genome ./travis_files/ -1 ./travis_files/test_R1.fastq.gz -2 ./travis_files/test_R2.fastq.gz"
  - "./deduplicate_bismark --bam test_R1_bismark_bt2_pe.bam"
  - "./bismark_methylation_extractor test_R1_bismark_bt2_pe.bam --gzip --CX --bed --genome ./travis_files/"
  - "./bismark2report"
  - "./bismark2summary"
  ## SE
  - "./bismark --genome ./travis_files/ ./travis_files/test_R1.fastq.gz"
  - "./deduplicate_bismark --bam test_R1_bismark_bt2.bam"
  - "./bismark_methylation_extractor test_R1_bismark_bt2.bam    --gzip --CX --bed --genome ./travis_files/"
 
  # Using Bowtie 1 results
  - "./bismark_genome_preparation --bowtie1 --verbose ./travis_files/"
  - "./bismark --genome ./travis_files/ --bowtie1 ./travis_files/test_R1.fastq.gz"
  - "./bismark --genome ./travis_files/ --bowtie1 -1 ./travis_files/test_R1.fastq.gz -2 ./travis_files/test_R2.fastq.gz"
  # Multicore
  - "./bismark --genome ./travis_files/ --parallel 4 -1 ./travis_files/test_R1.fastq.gz -2 ./travis_files/test_R2.fastq.gz"
  - "./bismark_methylation_extractor test_R1_bismark_bt2_pe.bam --gzip --CX --bed --parallel 8 --genome ./travis_files/"
  # coverage2cytosine
  - "./coverage2cytosine test_R1_bismark_bt2_pe.bismark.cov.gz --merge_CpG --genome ./travis_files/ -o test.output"
  - "./coverage2cytosine test_R1_bismark_bt2_pe.bismark.cov.gz --NOMe-seq --genome ./travis_files/ -o test.output"
  # bam2nuc
  - "./bam2nuc --genome_folder ./travis_files/ --genomic_composition_only"
  - "./bam2nuc --genome_folder ./travis_files/ test_R1_bismark_bt2_pe.bam"
  
  # Additional scenarios
  - "./bismark --pbat --genome ./travis_files/ -1 ./travis_files/test_R1.fastq.gz -2 ./travis_files/test_R2.fastq.gz"
  - "./bismark --non_directional --genome ./travis_files/ -1 ./travis_files/test_R1.fastq.gz -2 ./travis_files/test_R2.fastq.gz"
